server:
  port: 8084

spring:
  h2:
    console:
      enabled: true
      path: /h2
  r2dbc:
    driver-class-name: h2
    url: r2dbc:h2:mem:///data;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password: sa
    initialization-mode: always
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
